<?php

 /**
  * Implementation of hook_permission().
  */
 function ad_hoc_alerts_permission() {
   return array(
     'administer alerts' => array(
       'title' => t('Administer Ad Hoc Alerts'),
       'description' => t('Administer Ad Hoc Alerts'),
     ),
   );
 }

/**
 * Implements hook_menu().
 */
function ad_hoc_alerts_menu() {
  $items = array();

  $items['admin/config/user-interface/alerts'] = array(
    'title' => t('Ad Hoc Alerts'),
    'description' => 'A way for privileged users to post general alerts to site visitors.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ad_hoc_alerts_admin'), // An array of arguments to pass to the page callback function. Integer values pass the corresponding URL component.
    //'type' => MENU_NORMAL_ITEM, // One of MENU_NORMAL_ITEM / MENU_CALLBACK / MENU_SUGGESTED_ITEM / MENU_LOCAL_TASK / MENU_DEFAULT_LOCAL_TASK
    'file' => 'ad_hoc_alerts.admin.inc',
    'menu_name' => 'management', // Menu to place this item in.
    'access arguments' => array('administer library alerts'),
  );

  $items['ajax/ad-hoc-alert/load/view'] = array(
    'title' => 'Special Alerts',
    'type' => MENU_CALLBACK,
    'page callback' => 'ad_hoc_alerts_load_alerts_content',
    'access arguments' => array('access content'),
  );

  return $items;
}

/**
 * Loads ad hoc alerts markup.
 *
 * @return mixed
 *               returns rendered view or FALSE
 */
function ad_hoc_alerts_load_alerts_content() {

  $start = variable_get('ad_hoc_alerts_start_date');
  $end = variable_get('ad_hoc_alerts_end_date');
  if(is_array($start)){
    $start_time = mktime(0, 0, 0, $start['month'], $start['day'], $start['year']);
  } else {
    return;
  }
  if(is_array($end)){
      $end_time = mktime(23, 59, 59, $end['month'], $end['day'], $end['year']);
  } else {
    return;
  }
  $now = time();

  if(($start_time <= $now) && ($end_time >= $now)) {
      $alert = variable_get('ad_hoc_alerts_alert_text');
      $alert = '<div id="ad-hoc-alert">' . $alert . '</div>';
      echo $alert;
      exit(0);
  } else {
    variable_set('ad_hoc_alerts_start_date', '');
    variable_set('ad_hoc_alerts_end_date', '');
    variable_set('ad_hoc_alerts_end_date', '');

    return false;
  }

}
